# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_data_spring_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrecording',
            options={'ordering': ['session', '-class_part']},
        ),
        migrations.RemoveField(
            model_name='classrecording',
            name='class_date',
        ),
        migrations.RemoveField(
            model_name='classrecording',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classrecording',
            name='session_fk',
        ),
        migrations.AlterField(
            model_name='classrecording',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordings.CourseSession'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 27, 6, 59, 37, 494532)),
        ),
    ]
