# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_auto_20170527_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('github_url', models.URLField()),
                ('email', models.CharField(max_length=150)),
                ('slack_name', models.CharField(max_length=50)),
                ('slack_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='codewarsproblem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordings.CourseSession'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 16, 27, 56, 191098)),
        ),
    ]
