# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_auto_20170530_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recordings_path',
            field=models.FilePathField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionreference',
            name='gist_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreference',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreference',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 3, 53, 3, 893604)),
        ),
    ]
