# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_auto_20170603_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrecording',
            options={'ordering': ['-session', 'class_part']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='recordings_path',
        ),
        migrations.AddField(
            model_name='course',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 8, 59, 30, 367832)),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='num',
            field=models.PositiveIntegerField(verbose_name=b'Session Number'),
        ),
    ]
