# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_auto_20170603_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreference',
            name='kyu',
        ),
        migrations.AddField(
            model_name='codewarsproblem',
            name='kyu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='recordings.Course'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 23, 8, 21, 530587)),
        ),
    ]
